name: CI

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      branch:
        required: true
      commit_sha:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Checkout docs repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.branch }}
          path: docs
          fetch-depth: 1
      - run: |
          cp -r docs/.config/static/* static
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ github.event.inputs.commit_sha }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Deploy
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_DISPATCH }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'poc-aaa',
              repo: 'devops',
              workflow_id: 'common-docs.yaml',
              ref: 'main',
              inputs: {
                repo: '${{ github.event.inputs.repo }}',
                branch: '${{ github.event.inputs.branch }}',
                commit_sha: '${{ github.event.inputs.commit_sha }}',
              }
            })